version: '3.8'

services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual (.)
    build: .
    # Define um nome para o contêiner para fácil identificação
    container_name: api-imersao-devops-alura
    # Mapeia a porta 8000 do seu computador (host) para a porta 8000 do contêiner
    ports:
      - "8000:8000"
    # Monta o diretório atual do projeto no diretório /app do contêiner
    # Isso permite que as alterações no código sejam refletidas instantaneamente
    # no contêiner, aproveitando o --reload do uvicorn.
    # O banco de dados 'escola.db' também será criado e salvo no seu diretório local.
    volumes:
      - .:/app


# comando para executar o projeto: docker compose up